### ISSUE TITLE
core18 first login experience: out-of-the-blue reboot

### ISSUE THREAD

**Issue by panlinux** [snapcore/core18#171] opened 2020-09-22 13:04 UTC
Is this out-of-the-blue reboot expected?
```
andreas@nsnx:~/Downloads$ ssh ahasenack@localhost -p 8022
The authenticity of host '[localhost]:8022 ([127.0.0.1]:8022)' can't be established.
ECDSA key fingerprint is SHA256:2yPsCwbuTqJKkJyvpbr9l0eoykpC6gD8JiIccW6UMs0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of known hosts.
Welcome to Ubuntu Core 18 (GNU/Linux 4.15.0-112-generic x86_64)

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

 * Ubuntu Core:     https://www.ubuntu.com/core
 * Community:       https://forum.snapcraft.io
 * Snaps:           https://snapcraft.io

This Ubuntu Core 18 machine is a tiny, transactional edition of Ubuntu,
designed for appliances, firmware and fixed-function VMs.

If all the software you care about is available as snaps, you are in
the right place. If not, you will be more comfortable with classic
deb-based Ubuntu Server or Desktop, where you can mix snaps with
traditional debs. It's a brave new world here in Ubuntu Core!

Please see 'snap --help' for app installation and updates.
ahasenack@localhost:~$ snap list

Broadcast message from root@localhost (Tue 2020-09-22 12:59:44 UTC):

reboot scheduled to update the system
The system is going down for reboot NOW!

Connection to localhost closed by remote host.
Connection to localhost closed.
```

Incidentally, there was a long wait after `snap list` and before the broadcast appeared, I'd say close to a minute.

**Comment by anonymouse64** [comment] 2020-09-22 16:42
Yes after the system comes back, you should see inside `snap changes` a change for updating the core18 or pc-kernel snaps which always need a reboot and Ubuntu Core is setup to always check for refreshes as soon as the system boots up.

**Comment by montvid** [comment] 2020-12-20 20:59
it is by design - after it updates it reboots.

**Comment by anonymouse64** [comment] 2021-01-04 21:45
> Incidentally, there was a long wait after snap list and before the broadcast appeared, I'd say close to a minute.

also regarding this, this is also know this is likely because of a few reasons:
1. you could have run this command while snapd was updating itself, in which case systemd is holding onto the snapd socket but snapd is not using the socket yet, so when snapd finishes restarting after the update, then it responds
2. snapd could have shut itself down before trying to reboot for a core/kernel update, in which case you would see a long hang running `snap list` that doesn't return at all and instead waits for a reboot

**Comment by Meulengracht** [comment] 2024-04-08 10:14
This is somewhat expected with older images, the system will most likely update one of the essential snaps (i.e either core18, pc-kernel or the gadget), which will cause a reboot. I'll close this issue due to age, should there be a need to reopen this issue, please respond with the `snap changes` output so we can verify that the cause of the reboot was not due to a snap refresh.

**Closed as completed by Meulengracht** 2024-04-08 10:14 UTC
